apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web-front
  labels:
    app: mi-web-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-web-front
  template:
    metadata:
      labels:
        app: mi-web-front
    spec:
      containers:
        - name: mi-web-front-c
          image: fercdevv/proyecto1-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-front-svc
spec:
  type: NodePort
  selector:
    app: mi-web-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30089